### ISSUE TITLE
[feature] 建议自动引用(\autoref)增加对伪代码/算法的支持

### ISSUE THREAD

**Issue by lyh458** [sikouhjw/gdutthesis#100]
- 问题：`\autoref`不支持伪代码/算法
- MWE：
```latex
\documentclass[]{gdutthesis}
\usepackage[linesnumbered, ruled, lined, boxed,commentsnumbered]{algorithm2e}[1]

\begin{document}

测试算法\ref{pseudocode_zh}

测试\autoref{pseudocode_zh}

\renewcommand{\algorithmcfname}{算法}
\SetKwInput{KwIn}{输入}
\SetKwInput{KwOut}{输出}

\begin{algorithm}[H]
  \label{pseudocode_zh}
  \SetAlgoLined
  \KwIn{路径集合 $\mathcal{W} $ }

  \KwOut{ 节点的嵌入式表示 $\mathbb{R}$ }

  \ForEach{$v_j$ in $\mathcal{W}_{v_i}$}
  {
    \ForEach{$u_k \in \mathcal{W}_{v_i}  \left[ j-w : j +w  \right] $}
    {
      $J(\Phi) = - log P\left( u_k | \Phi  ( v_j) \right)$ \;
      $\Phi = \Phi - \alpha * \frac{\partial J}{\partial \Phi }$ \;

    }
  }
  \caption{利用跳元(Skip-Gram)模型更新节点嵌入参数}
\end{algorithm}
\end{document}
```
![2023-05-26_11-57](https://github.com/sikouhjw/gdutthesis/assets/13861056/dd5856b1-3d3f-4005-ae3c-fffaeb7585ca)

- 需求：(1) `\autoref`支持伪代码/算法；(2) 伪代码/算法根据所在章自动编号

**Comment by sikouhjw** [comment]
也许 thuthesis 那样『按需加载』宏包，模板根据加载的宏包去适配或许更好
```tex
\documentclass{gdutthesis}
\usepackage[algochapter]{algorithm2e}
\ExplSyntaxOn
\cs_set:cpn { algorithmautorefname } { 算法 }
\ExplSyntaxOff
\begin{document}

\mainmatter

\chapter{测试}{test}

算法~\ref{pseudocode_zh}

\autoref{pseudocode_zh}

\begin{algorithm}
  \caption{test}\label{pseudocode_zh}
\end{algorithm}

\end{document}
```

**Comment by lyh458** [comment]
这样子也挺好。主要是希望能统一一种引用的方式，要不然图片、表格那些用了`\autoref`，算法又得用`\ref`（而且不能根据章节编号）。
---
如果可能的话更新一下用户文档，供后人参考。

**Comment by lyh458** [comment]
补充一下，格式检查系统要求伪代码根据章节编号，并且使用连字符“-”（hyphen），例如：算法1-1。
![image](https://github.com/sikouhjw/gdutthesis/assets/13861056/26c222f5-162c-47f1-8fd7-7056719aa4b7)

但是按照现有模板无法实现以上要求，即使按照`example/algorithm.tex`中使用`algochapter`选项，编译得到的效果是dash，例如：算法1.1。
![image](https://github.com/sikouhjw/gdutthesis/assets/13861056/88f71974-7bcd-4554-9d30-1f7f3506193a)

---

简单的解决方案：
- 首先添加`algochapter`选项，即
```latex
\usepackage[algochapter]{algorithm2e}
```
- 然后在伪代码的`\begin{algorithm}`下添加：
```latex
\renewcommand{\thealgocf}{\thechapter-\arabic{algocf}}
```
FYI.

**Comment by sikouhjw** [comment]
> 补充一下，格式检查系统要求伪代码根据章节编号，并且使用连字符“-”（hyphen），例如：算法1-1。

没有文件说明算法需要使用 `1-1` 的格式。



> 但是按照现有模板无法实现以上要求，即使按照`example/algorithm.tex`中使用`algochapter`选项，编译得到的效果是dash，例如：算法1.1。 ![image](https://user-images.githubusercontent.com/13861056/284111461-88f71974-7bcd-4554-9d30-1f7f3506193a.png)

不是 `dash`，是 `dot`。


> 简单的解决方案：
> 
>     * 首先添加`algochapter`选项，即
> 
> 
> ```
> \usepackage[algochapter]{algorithm2e}
> ```
> 
>     * 然后在伪代码的`\begin{algorithm}`下添加：
> 
> 
> ```
> \renewcommand{\thealgocf}{\thechapter-\arabic{algocf}}
> ```


后续修改。

**Comment by sikouhjw** [comment]
> 为啥Overleaf的版本不行啊，楼主可否帮忙测试一下，小白不知道问题在哪[笑哭]

只需要第 27 行，其余 25-26、28 行是不需要的。如果需要 `algorithm2e` 宏包的其他功能，按需添加选项。

**Comment by sikouhjw** [comment]
https://github.com/sikouhjw/gdutthesis/commit/0f3745127922c301296a210dcdcd5de119c00dce
