### ISSUE TITLE
[feature] `footnote`支持章与章之间的连续编号

### ISSUE THREAD

**Issue by lyh458** [sikouhjw/gdutthesis#101]
- 问题：
使用当前的`gdutthesis.cls`，章与章之间如果都设置了`\footnote{}`，其编号并不是连续的，在新的一章会自动从1开始。

- MWE：
```
\documentclass{gdutthesis}

% \counterwithout{footnote}{chapter}

\begin{document}

\mainmatter

\chapter{测试1}{test1}

脚注\footnote{脚注脚注脚注脚注脚注}

脚注\footnote{脚注脚注脚注脚注脚注}

\chapter{测试2}{test2}

脚注\footnote{脚注脚注脚注脚注脚注}

脚注\footnote{脚注脚注脚注脚注脚注}

\end{document}
```

- 需求：
`\footnote{}`支持章与章之间的连续编号。

- 解决办法：
在`\begin{document}`前添加`\counterwithout{footnote}{chapter}`，参考[Continuous footnote numbering](https://tex.stackexchange.com/questions/10448/continuous-footnote-numbering)

---
PS: 
- 这可能是比较小众的需求，但是如果遇到这种情况，从逻辑上讲应该是要求连续编号的（虽然脚注就在当前页）;
- 这可能是比较小众的需求，不确定是否需要在`gdutthesis.cls`中集成，这个issue和上面的**解决办法**仅供参考。

**Comment by sikouhjw** [comment]
我校没有要求脚注的样式，我查了几个大学关于『脚注』的规定，都要求『新的一页要重新排序』。

脚注一般用来说明注释性的文本或给出参考文献，不需要连续编号。
