### ISSUE TITLE
关于`博士学位`英文翻译的规范问题

### ISSUE THREAD

**Issue by lyh458** [sikouhjw/gdutthesis#106]
在学校颁布的论文撰写规范中，将`博士学位`翻译为`Doctor of <>`，如：`Doctor of Engineering Science`。但上周六旁听了一场博士答辩，专家指出：`博士`在英文里面是`Doctor of Philosophy`，学校这样翻译是不规范的。我查了一下，在英文中一般说某个领域的博士，所以建议翻译为：`Doctor of Philosophy in <>`。
仅供参考。

**Comment by note286** [comment]
在这里提没有什么意义，可以直接向学校反馈。

**Comment by sikouhjw** [comment]
https://github.com/sikouhjw/gdutthesis/blob/8101458f222ada2c987de5548bfff10aa762bc92/gdutthesis.cls#L1991
https://github.com/sikouhjw/gdutthesis/blob/8101458f222ada2c987de5548bfff10aa762bc92/main.tex#L106
这是属于「主观能动性」的范畴，可以由用户自行修改。

用户按照学校规范去写 `Doctor of xx` 我也没办法。

已反馈给相关人员。
