### ISSUE TITLE
关于`\mathbb{}`的渲染问题

### ISSUE THREAD

**Issue by lyh458** [sikouhjw/gdutthesis#109]
偶然发现`\mathbb{}`这个类型语法使用`gdutthesis`渲染出来的效果与期望的效果存在较大差异。MWE:
```latex
\documentclass[]{gdutthesis}

\begin{document}
$\boldsymbol{K} \in \mathbb{R}^{3 \times 2}$
\end{document}
```
- 使用`gdutthesis`渲染效果示例：
![image](https://github.com/sikouhjw/gdutthesis/assets/13861056/2a655c70-ab99-4d4e-bf03-4be2f5a81cdd)

- 期望效果示例：
![image](https://github.com/sikouhjw/gdutthesis/assets/13861056/7f8e99ea-7180-4d39-a879-8edad59824f5)

**Comment by sikouhjw** [comment]
字体问题，`unicode-math` 宏包下的 `\mathbb` 就是长这个样。
```tex
\documentclass{article}
\usepackage{unicode-math}
\begin{document}
$\mathbb R$
\end{document}
```

建议接受，`unicode-math` 几乎是数学字体最好的方案。

PS: 粗体建议使用 `unicode-math` 的 `\symbf`，或者 `\renewcommand{\bf}{\symbf}`。教程看：https://github.com/sikouhjw/gdutthesis/wiki/math
