### ISSUE TITLE
使用`gdutthesis`时，`\symbf`显示的是带斜加粗效果

### ISSUE THREAD

**Issue by lyh458** [sikouhjw/gdutthesis#110]
偶然看到[这个issue](https://github.com/sikouhjw/gdutthesis/discussions/34#discussioncomment-6998367)的推送，想起之前听从建议使用`\symbf`替代`\boldsymbol`的显示效果是带有斜体的加粗，但我没有用`\symbfit`啊？？？
- MWE 1 (使用gdutthesis):
```latex
\documentclass[]{gdutthesis}

\begin{document}

$\symbf{ABC}$
$\symbfit{ABC}$

\end{document}
```
- 显示效果1(使用gdutthesis):
![image](https://github.com/sikouhjw/gdutthesis/assets/13861056/6bb32638-dfa3-4bfc-8d9b-6b9d2db80f47)

- MWE  2(不使用gdutthesis，额外导入`unicode-math`包):
```latex
\documentclass{article}
\usepackage{unicode-math}
% \documentclass[]{gdutthesis}

\begin{document}

$\symbf{ABC}$
$\symbfit{ABC}$

\end{document}
```
- 显示效果2(不使用gdutthesis，额外导入`unicode-math`包):
![image](https://github.com/sikouhjw/gdutthesis/assets/13861056/f32de6bb-2f46-42c5-9923-d8dcf67a6bda)

**Comment by sikouhjw** [comment]
模板添加了符合写作习惯的设置
https://github.com/sikouhjw/gdutthesis/blob/928ba3cd8e67a3ea625260eed1e07d54440dcaae/gdutthesis.cls#L849-L853

**Comment by lyh458** [comment]
好吧，明白了！多谢！
