### ISSUE TITLE
公式前后行距不一致（前行距大、后行距小）

### ISSUE THREAD

**Issue by lyh458** [sikouhjw/gdutthesis#112]
- **问题**：公式前后行距不一致（前行距大、后行距小），示例效果如下：
![image](https://github.com/sikouhjw/gdutthesis/assets/13861056/1ff1ba7b-4535-4efd-b3db-6a4aa17b5e8e)
Issue #22 也提到了相似的问题，但是我十分确认公式前并没有空行；而且查看上届毕业同门论文中的公式（也是使用gdutthesis模板），发现也存在该问题。

- **论文模板要求（202309）**：包含公式的段落行间距可设置为段前和段后6磅，1.5倍行距，以保证公式完全显示。

- **MWE**：
```latex
\begin{document}
前前前前前前前前前前前前前前前前前前前前前前前前前前前
\begin{equation}
    A+B=C
\end{equation}
后后后后后后后后后后后后后后后后后后后后后后后后后后后
\end{document}
```

**Comment by sikouhjw** [comment]
https://github.com/sikouhjw/gdutthesis/discussions/34 写了怎么调制数学公式前后行距。以下是一个调整例子：
```tex
\documentclass{gdutthesis}
\ExplSyntaxOn
\ctex_after_end_preamble:n
  {
    \setlength{\abovedisplayskip}{0.15\baselineskip}
    \setlength{\belowdisplayskip}{0.15\baselineskip}
    \setlength{\abovedisplayshortskip}{\baselineskip-\ccwd+0.15\baselineskip}
    \setlength{\belowdisplayshortskip}{0.15\baselineskip}
  }
\ExplSyntaxOff
\begin{document}
\mainmatter

正文文字正文文字正文文字正文文字正文文字正文文字正文文字正文文字正文文
字正文文字正文文字正文文字正文文字正文文字正文文字正文文字正文文字正文文字
正文文字正文文字正文文字正文文字正文文字正文文字。
\begin{equation}
  \frac{dx}{dt} = K (1-x)
\end{equation}
正文文字正文文字正文文字正文文字正文文字正文文字正文文字正文文字正文文
字正文文字正文文字正文文字正文文字正文文字正文文字正文文字正文文字正文文字
正文文字正文文字正文文字正文文字正文文字正文文字。
\end{document}
```
以及调整后与「格式模板」的对比图。
![图片](https://github.com/sikouhjw/gdutthesis/assets/49770925/613cc9c2-2b4c-4a5b-a621-0e4046f7dbe1)

**Comment by lyh458** [comment]
查看 #34，我也实际测试了，发现导言增加这些设置还是没能很好解决前后重叠的问题；要想得到相对理想的效果，还是使用如你在其中给出的方案：放弃`equation`环境而使用`align`或者`gather`。
