### ISSUE TITLE
表格与文字的排版问题

### ISSUE THREAD

**Issue by Xuezhenggdut** [sikouhjw/gdutthesis#119]
![image](https://github.com/sikouhjw/gdutthesis/assets/46556712/5ed0fd72-bf47-43dc-8347-057293a83bb7)
表格上下都有文字，直接跳过表格这页了，不能排版到表格上下周围。

\usepackage{multirow}
\usepackage{booktabs}
\usepackage{colortbl}

\begin{table}
%\vspace{-2.3cm}
\bicaption{不同融合策略目标检测性能}{Performance of object detection with different fusion strategies}%标题
\label{tab:fusion_results}
\centering
%\arrayrulecolor{black}
\begin{tabular}{c|c|ll} 
\toprule
\multirow{2}{*}{骨干网络}                &
\multirow{2}{*}{融合策略}                  & \multicolumn{2}{c}{AP@IoU}                                 \\ 
\arrayrulecolor{black}\cline{3-4}
                            &             & \multicolumn{1}{c}{0.5}   & \multicolumn{1}{c}{0.7}    \\ 
%\arrayrulecolor{black}
\hline
\multirow{5}{*}{PointPillar} & 早期融合                  & \multicolumn{1}{c}{\textbf{0.913}} & \multicolumn{1}{c}{\textbf{0.839}}  \\
                             & 后期融合              & \multicolumn{1}{c}{0.815} & \multicolumn{1}{c}{0.747}  \\
                             & Attentive Fusion (中期融合) & \multicolumn{1}{c}{0.871} & \multicolumn{1}{c}{0.811}  \\
                             & Where2comm (中期融合)       & \multicolumn{1}{c}{0.843} & \multicolumn{1}{c}{0.705}  \\
                             & 中期融合        & \multicolumn{1}{c}{0.879} & \multicolumn{1}{c}{0.811}  \\ 
\hline
\multirow{3}{*}{SECOND}      & 早期融合                  & 0.877                     & 0.813                      \\
                             & 后期融合                & \multicolumn{1}{c}{0.846} & \multicolumn{1}{c}{0.775}  \\
                             & 中期融合 & \textbf{0.903}                     & \textbf{0.856}                      \\ 
\hline
\multirow{3}{*}{VoxelNet}    & Cooper (早期融合)                   & 0.852                     & 0.758                      \\
                             & 后期融合                & 0.801                     & 0.738                      \\
                             & F-Cooper (中期融合)  & \textbf{0.906}                     & \textbf{0.864}                      \\ 
\hline
\multirow{3}{*}{PIXOR}       & 早期融合                   & 0.810                     & 0.678                       \\
                             & 后期融合                &  0.769                     &      0.578                 \\
                             & 中期融合  & \textbf{0.815}                     & \textbf{0.687}                      \\
\bottomrule
\end{tabular}
\end{table}

**Comment by sikouhjw** [comment]
1. 三线表不需要竖线
2. https://github.com/sikouhjw/gdutthesis/discussions/73#discussioncomment-8353186
