### ISSUE TITLE
图片总是出现在页面顶部

### ISSUE THREAD

**Issue by TsingWei** [sikouhjw/gdutthesis#121]
经过测试，在overleaf(xelatex)和ubuntu+texlive2023(latexmk -xe)两个环境下，以下几种情况图片始终都不按期望的出现在页面顶部：
1. 不带参数: ```\begin{figure}```
2. 带参数h: ```\begin{figure}[h]```
3. 带参数!h: ```\begin{figure}[!h]```
4. ```\usepackage{float}```的情况下带H参数: ```\begin{figure}[H]```

是哪里特意设置的吗？
![image](https://github.com/sikouhjw/gdutthesis/assets/28723968/00e49f2f-81ed-412e-b1c5-d544b23a3aed)

**Comment by TsingWei** [comment]
刚刚试了下在`main.tex`中把`\gdutsetup->free-float`设置为`false`就解决了，但不懂会不会造成其他排版问题。

**Comment by sikouhjw** [comment]
看 https://github.com/sikouhjw/gdutthesis/discussions/73 和[模板手册](https://github.com/sikouhjw/gdutthesis/releases/latest/download/gdutthesis.pdf)

**Comment by TsingWei** [comment]
之前写小论文的时候确实是默认顶部或者底部（IEEEtran_HOWTO里写的），个人感觉是因为外文的习惯加上双栏，确实插在文字中间这一方式不够美观。但是这里中文单栏，再加上学校给的word模板里给的就是插在文字中间，导致我以为就是要这样。不过既然 #73 都这么说了，那就放顶部吧。

**Comment by sikouhjw** [comment]
想改的话，将 `!tp` 改成 `!h`
https://github.com/sikouhjw/gdutthesis/blob/0f3745127922c301296a210dcdcd5de119c00dce/gdutthesis.cls#L1183-L1189
