### ISSUE TITLE
空白声明页的位置

### ISSUE THREAD

**Issue by Xuezhenggdut** [sikouhjw/gdutthesis#122]
广东工业大学研究生学位论文格式模板（2023年9月修订）
空白声明页的位置已经放到了摘要前面！
![image](https://github.com/sikouhjw/gdutthesis/assets/46556712/98ee895a-682d-480d-a5a2-48981640c9e3)
![image](https://github.com/sikouhjw/gdutthesis/assets/46556712/eeb9d87c-bd85-4b17-9734-0e3d10d81d38)

**Comment by sikouhjw** [comment]
https://github.com/sikouhjw/gdutthesis/blob/0f3745127922c301296a210dcdcd5de119c00dce/main.tex#L116-L122
不用最新模板导致格式审查出现问题，与模板无关
https://github.com/sikouhjw/gdutthesis/blob/0f3745127922c301296a210dcdcd5de119c00dce/main.tex#L11
