### ISSUE TITLE
请问这个是什么原因？两个中文名字挤到一起了，没有逗号

### ISSUE THREAD

**Issue by yaunsine** [sikouhjw/gdutthesis#123]
![image](https://github.com/sikouhjw/gdutthesis/assets/54234422/4fba312d-0985-49b0-93ed-ce91e917da5a)

![image](https://github.com/sikouhjw/gdutthesis/assets/54234422/f9df970a-fc40-4cab-af83-96c6838cdfb1)

**Comment by sikouhjw** [comment]
请使用谷歌学术导出 bib 文献。
```tex
@article{刘树栋2015基于位置的社会化网络推荐系统,
  title={基于位置的社会化网络推荐系统},
  author={刘树栋 and 孟祥武},
  journal={计算机学报},
  volume={38},
  number={2},
  pages={322--336},
  year={2015}
}
```

**Comment by yaunsine** [comment]
> 请使用谷歌学术导出 bib 文献。
> 
> ```
> @article{刘树栋2015基于位置的社会化网络推荐系统,
>   title={基于位置的社会化网络推荐系统},
>   author={刘树栋 and 孟祥武},
>   journal={计算机学报},
>   volume={38},
>   number={2},
>   pages={322--336},
>   year={2015}
> }
> ```

已解决，谢谢
