### ISSUE TITLE
封面问题？

### ISSUE THREAD

**Issue by yaunsine** [sikouhjw/gdutthesis#126]
封面如何启用最新版

**Comment by sikouhjw** [comment]
你的问题描述不够清楚。现在为什么不是最新版？哪里不够新？哪里不满足你的需求？

**Comment by yaunsine** [comment]
作者您好，我之前下载的学校提供的版本，需要封面是不对的，有哪里什么修改的：
![image](https://github.com/sikouhjw/gdutthesis/assets/54234422/d0b3a951-60c9-46d7-ad55-df797d402ce0)

**Comment by yaunsine** [comment]
![image](https://github.com/sikouhjw/gdutthesis/assets/54234422/186a604f-cff7-4886-bcf3-e2424421a82c)

**Comment by yaunsine** [comment]
这是word最新版本：
![image](https://github.com/sikouhjw/gdutthesis/assets/54234422/b6a5b6b1-d97f-45d3-a5b8-3c3679d6b011)

**Comment by yaunsine** [comment]
> 你的问题描述不够清楚。现在为什么不是最新版？哪里不够新？哪里不满足你的需求？

**Comment by sikouhjw** [comment]
下载最新版，这个问题就解决了。这个通知是哪个学院发的？
https://github.com/sikouhjw/gdutthesis/archive/refs/heads/main.zip

**Comment by yaunsine** [comment]
> 下载最新版，这个问题就解决了。这个通知是哪个学院发的？ https://github.com/sikouhjw/gdutthesis/archive/refs/heads/main.zip

计算机学院 :clown_face:

**Comment by yaunsine** [comment]
好的，谢谢

**Comment by TsingWei** [comment]
> > 下载最新版，这个问题就解决了。这个通知是哪个学院发的？ https://github.com/sikouhjw/gdutthesis/archive/refs/heads/main.zip
> 
> 计算机学院 🤡

我也是计算机，为啥我们没收到通知？总感觉自己用latex爹不管娘不要的。

**Comment by sikouhjw** [comment]
> 我也是计算机，为啥我们没收到通知？总感觉自己用latex爹不管娘不要的。

可能是不同团队的通知不同吧，有些 leader 用 latex，就会要求学生用。

自动化这边用的比较普及。
