### ISSUE TITLE
请问能否改变新章节只能在奇数页这个设定

### ISSUE THREAD

**Issue by tengxiao24** [sikouhjw/gdutthesis#13]
如果上一章节在奇数页结束，那么新的章节和上一章节之间就会存在一张空白页，不知能否修改。

**Comment by sikouhjw** [comment]
https://github.com/sikouhjw/gdutthesis/commit/f1a22af52e9a7d14d47ce64cce1359fda863c391 添加了 `open` 选项，`open=true` 就可以不分奇偶页输出新的章节。
