### ISSUE TITLE
论文封面问题

### ISSUE THREAD

**Issue by yaunsine** [sikouhjw/gdutthesis#130]
作者你好，论文模板存在以下问题：
1、彩色封面和封底没有分开
2、封面日期需为阿拉伯数字写法（2024年5月）

是否可以指导下如何修改
![image](https://github.com/sikouhjw/gdutthesis/assets/54234422/d8e708f1-5443-4f9f-b4d5-915b373c6c60)

![image](https://github.com/sikouhjw/gdutthesis/assets/54234422/e387eda2-3a1a-4d70-be28-9eaea54a6da2)

**Comment by sikouhjw** [comment]
0. 模板没有问题。
1. 封面和封底分开，不是明文规定，是学院的通知。参考 https://github.com/sikouhjw/gdutthesis/discussions/74#discussioncomment-9759976.
2. 没有任何规定规定了答辩年月的格式，你可以将
    https://github.com/sikouhjw/gdutthesis/blob/0f3745127922c301296a210dcdcd5de119c00dce/gdutthesis.cls#L1936-L1938
    的 1937 行替换为 `& 2024 年 5 月`

**Comment by yaunsine** [comment]
> 0. 模板没有问题。
> 1. 封面和封底分开，不是明文规定，是学院的通知。参考 [根据《学位论文审核的格式要求说明》修改模板选项 #74 (comment)](https://github.com/sikouhjw/gdutthesis/discussions/74#discussioncomment-9759976).
> 2. 没有任何规定规定了答辩年月的格式，你可以将
>    https://github.com/sikouhjw/gdutthesis/blob/0f3745127922c301296a210dcdcd5de119c00dce/gdutthesis.cls#L1936-L1938
>    
>    的 1937 行替换为 `& 2024 年 5 月`

好的，谢谢！！
