### ISSUE TITLE
页眉问题

### ISSUE THREAD

**Issue by yaunsine** [sikouhjw/gdutthesis#131]
作者您好，我的页眉里面是“广东工业大学硕士专业学位论文”，请问这里如何修改，应该修改为“广东工业大学硕士学位论文”
![image](https://github.com/sikouhjw/gdutthesis/assets/54234422/f04f096f-6ca6-490e-a477-7caa2b945a0d)

**Comment by yaunsine** [comment]
> 作者您好，我的页眉里面是“广东工业大学硕士专业学位论文”，请问这里如何修改，应该修改为“广东工业大学硕士学位论文” ![image](https://private-user-images.githubusercontent.com/54234422/340548942-f04f096f-6ca6-490e-a477-7caa2b945a0d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2ODg4NzMsIm5iZiI6MTcxODY4ODU3MywicGF0aCI6Ii81NDIzNDQyMi8zNDA1NDg5NDItZjA0ZjA5NmYtNmNhNi00OTBlLWE0NzctN2NhYTJiOTQ1YTBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE4VDA1MjkzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0MDY0MjRkZGE1ODYxYzYyZTY2NTczZTI0ODk0MWQwY2ExODQwOGNhN2MwMTI5Y2UxNzQ5MDUyODk3ZGNkOTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9cYLClE4oOTlPAX2dt1-LL3qwTpJ0eg8RXkr_K8oyIw)

![image](https://github.com/sikouhjw/gdutthesis/assets/54234422/e239fcdc-6c30-4aa9-90d6-c9ecb366b952)

**Comment by yaunsine** [comment]
![image](https://github.com/sikouhjw/gdutthesis/assets/54234422/b3a6c23a-d658-4a76-b5f2-4da5a01ec29e)
改了这个地方

**Comment by sikouhjw** [comment]
https://github.com/sikouhjw/gdutthesis/blob/0f3745127922c301296a210dcdcd5de119c00dce/gdutthesis.cls#L170-L171
将
```tex
{ 博士学位, 硕士学位, 硕士专业学位 }
```
改为
```tex
{ 博士学位, 硕士学位, 硕士学位 }
```
即可实现全局替换，包括页眉和扉页。
