### ISSUE TITLE
XeLaTex编译时间过久

### ISSUE THREAD

**Issue by liu2048** [sikouhjw/gdutthesis#133]
VS Code配置的latex环境，Texlive 2020，用XeLatex编译时间太久（需要半小时以上，应该不太正常）。是Texlive 版本太低了吗

**Comment by note286** [comment]
用cmd命令编译，例如`xelatex thesis`，查看卡在哪一步，可以截图。

**Comment by liu2048** [comment]
![image](https://github.com/user-attachments/assets/71b325d3-5df0-4180-9f7f-13fa5023ec88)
![image](https://github.com/user-attachments/assets/4dccb1d5-6e82-4351-9a66-f054f30c2ad4)
这样的

**Comment by note286** [comment]
安装TeX Live 2024吧，把旧版本卸载掉。

**Comment by liu2048** [comment]
我装了新版本，现在电脑上有两个版本，直接删掉2020这个文件夹吗？能不能切换版本啊
![image](https://github.com/user-attachments/assets/aa1b4a4e-ed94-4090-8ee1-cad161bc27b5)

**Comment by note286** [comment]
环境变量里把2024的放在2020上面，然后重新开一个cmd编译试试。

**Comment by liu2048** [comment]
可以了，非常感谢，帮了我大忙了
