### ISSUE TITLE
对参考文献格式的疑问

### ISSUE THREAD

**Issue by tengxiao24** [sikouhjw/gdutthesis#16]
作者您好，我用gdutthesis模板生成的参考文献 作者名称全部都是大写，学校给的模板我看了一下是首字母大写。不知这里是否存在问题。

**Comment by sikouhjw** [comment]
`texdoc gbt7714` 提供了 `gbt7714-2005-numerical.bst`，直接调用即可，这是使用者的自由。

PS：本科的规定更加离谱，规定是 GB/T 7714-1987。

**Comment by sikouhjw** [comment]
> PS：本科的规定更加离谱，规定是《GB/T 7714-1987》

在《2022届毕业设计（论文）手册》[^1]中，参考文献规范已修改为《GB/T 7714-2015》
> 参考文献的著录应按中华人民共和国国家标准 GB/T 7714—2015 《信息与文献参考文献著录规则》执行。

[^1]: https://jwc.gdut.edu.cn/system/_content/download.jsp?urltype=news.DownloadAttachUrl&owner=1687414050&wbfileid=7575173
