### ISSUE TITLE
公式与上文相隔过远的问题

### ISSUE THREAD

**Issue by SiriusFang2020** [sikouhjw/gdutthesis#22]
你好，请问像图片里公式跟上文隔得特别远，但是跟下文就是正常的距离，这个问题该怎么解决呢
![4981646913766_ pic](https://user-images.githubusercontent.com/59632817/157658307-46e8072d-242f-43d8-ab1c-e8cfb9e774a7.jpg)
？

**Comment by sikouhjw** [comment]
公式前面是不是有空行？

**Comment by SiriusFang2020** [comment]
并没有呢
![image](https://user-images.githubusercontent.com/59632817/157661942-d9d092cc-5d26-4301-86eb-bee10c207d6f.png)

**Comment by SiriusFang2020** [comment]
不好意思，截错图了，经测试确实是空行的问题，多谢🙏
