### ISSUE TITLE
模板行距问题

### ISSUE THREAD

**Issue by O3OTZ** [sikouhjw/gdutthesis#6]
你好，作者提供的模板生成的目录跟学校论文撰写规范里的目录行距不一样，作者的是单倍行距，而学校的是1.5倍行距，请问怎么修改。

**Comment by sikouhjw** [comment]
> 
> 
> 你好，作者提供的模板生成的目录跟学校论文撰写规范里的目录行距不一样，作者的是单倍行距，而学校的是1.5倍行距，请问怎么修改。

1. 您想说的是 `广东工业大学研究生学位论文撰写规范格式模板.docx` 中的目录的行间距显著大于模板的行间距
2. 本模板已设置为『1.5倍行距』
3. Word 的间距大于本模板，是因为设置了『如果定义了文档网格，则对齐到网格』
4. `撰写规范.docx` 没有提到『如果定义了文档网格，则对齐到网格』
5. LaTeX 做不到『如果定义了文档网格，则对齐到网格』的效果

**Comment by O3OTZ** [comment]
好的，谢谢。

**Comment by sikouhjw** [comment]
> 
> 
> > 你好，作者提供的模板生成的目录跟学校论文撰写规范里的目录行距不一样，作者的是单倍行距，而学校的是1.5倍行距，请问怎么修改。
> 
>     1. 您想说的是 `广东工业大学研究生学位论文撰写规范格式模板.docx` 中的目录的行间距显著大于模板的行间距
> 
>     2. 本模板已设置为『1.5倍行距』
> 
>     3. Word 的间距大于本模板，是因为设置了『如果定义了文档网格，则对齐到网格』
> 
>     4. `撰写规范.docx` 没有提到『如果定义了文档网格，则对齐到网格』
> 
>     5. LaTeX 做不到『如果定义了文档网格，则对齐到网格』的效果

第三点说的不够全面，是 `广东工业大学研究生学位论文撰写规范格式模板.docx` 同时设置了『如果定义了文档网格，则对齐到网格』和『只指定行网络』，且设置为『每页42行』，这与 `撰写规范.docx` 中的『论文每页 30 行，每行 36 字』矛盾。

归纳一下：
1. `广东工业大学研究生学位论文撰写规范格式模板.docx` 中的要求
    - 1.5 倍行距
    - 如果定义了文档网格，则对齐到网格
    - 只指定行网络
    - 每页 42 行
2. `撰写规范.docx` 中的要求
    - 论文每页 30 行
    - 五处提到『行距』的地方，有四个均为『1.5倍行距』
3. 模板的实现
   - 只设置了『1.5倍行距』

解决方案：
- 以 `广东工业大学研究生学位论文撰写规范格式模板.docx` 为准，调整行距使得效果一致
- 以 `撰写规范.docx` 为准，调整行距使得效果一致

**Comment by sikouhjw** [comment]
我制作了一份[对比文件](https://github.com/sikouhjw/gdutthesis/files/7563086/default.zip)：
1. `test1.pdf` 是用 LaTeX 生成的『1.5倍行距』的文档
2. `test2.pdf` 是用 Word 生成的『1.5倍行距，无对齐网络』的文档
3. `test3.pdf` 是用 Word 生成的『1.5倍行距，只指定行网络，每页 42 行，「如果定义了文档网格，则对齐到网格」』的文档
4. `diff.pdf` 是 `test1.pdf` 与 `test2.pdf`、`test3.pdf` 之间的对比

![图片](https://user-images.githubusercontent.com/49770925/142424405-5f82ba50-b266-43c4-8da7-b2333551a542.png)

**Comment by sikouhjw** [comment]
如果按 `广东工业大学研究生学位论文撰写规范格式模板.docx` 来做，行距应设置为 `1.568`。
![图片](https://user-images.githubusercontent.com/49770925/142445125-2f1f01ce-b4ac-4816-987f-209bd1938fe8.png)

**Comment by O3OTZ** [comment]
您好，现在是打算以哪种要求为准，`撰写规范.docx`OR`广东工业大学研究生学位论文撰写规范格式模板.docx`

**Comment by sikouhjw** [comment]
1. 我仔细看了一下模板的行距，发现有点问题
2. `\gdutmaketitle` 把后面的行距弄成默认行距了
3. 临时解决方案是在导言区加上
   ```tex
   \ExplSyntaxOn
   \makeatletter
   \ctex_after_end_preamble:n
     {
       \linespread{\ZhLS@bodylinespread}\selectfont
     }
   \makeatother
   \ExplSyntaxOff
   ```
4. 准备把行距改成 `1.568`，来近似 `广东工业大学研究生学位论文撰写规范格式模板.docx` 的效果
5. 因为大多数人用 Word 应该都是在 `广东工业大学研究生学位论文撰写规范格式模板.docx` 的基础上改的

**Comment by sikouhjw** [comment]
https://github.com/sikouhjw/gdutthesis/commit/85d6d71b26f3be01fef1b6c5fa5b2c7935a5d2fc
