### ISSUE TITLE
多导师的封面、扉页处理

### ISSUE THREAD

**Issue by sikouhjw** [sikouhjw/gdutthesis#65]
1. 封面的『导师姓名』不需要职称。
   需要将姓名和职称分开输入。
2. 当出现多导师时，封面和扉页需要做不同的处理。
   - 双导师时，封面输出第一导师，扉页输出第一、第二导师；
   - 三导师时，封面输出第一、第二导师，扉页输出第一、第二、第三导师，并将原第二导师的空白位置修改为『企业导师』。

**Comment by sikouhjw** [comment]
https://github.com/sikouhjw/gdutthesis/commit/2ba2cc0f0751317347dd7877d6336fef45b66f48

**Comment by mycano** [comment]
单导师但是不希望显示双导师之类字的时候可以修改gdutthesis.cls文件，在1906行左右。修改后的代码如下：

\multirow{6}*
        {
          \begin{CJKfilltwosides*}{0pt}
             \\
            指导教师姓名、职称：\\
            % 校外指导教师姓名、职称：\\
            学科（专业）或领域名称：\\
            学生所属学院：\\
            答辩委员会主席：\\
            论文答辩日期：
          \end{CJKfilltwosides*}
        }
        &  \\
        & \l__gdut_info_supervisor_name_tl \gdut_name_jobname_spacer: \l__gdut_info_supervisor_jobname_tl \\
        \cline{2-2} 

具体的修改过程在这种图中：
![9bf199f29083a1604422e4cd5d90bd9](https://user-images.githubusercontent.com/44746611/223132470-c7837669-35b5-4f2e-9243-17fbfbe9d4ee.png)

**Comment by sikouhjw** [comment]
> 单导师但是不希望显示双导师之类字

校外指导教师姓名、职称

**Comment by sikouhjw** [comment]
> 单导师但是不希望显示双导师之类字的时候可以修改gdutthesis.cls文件，在1906行左右。修改后的代码如下：


封面的校外指导教师是学校的规定

**Comment by coallar** [comment]
> [2ba2cc0](https://github.com/sikouhjw/gdutthesis/commit/2ba2cc0f0751317347dd7877d6336fef45b66f48)

直接更改后，校外指导老师一栏就没有了，会有影响吗

**Comment by sikouhjw** [comment]
> > [2ba2cc0](https://github.com/sikouhjw/gdutthesis/commit/2ba2cc0f0751317347dd7877d6336fef45b66f48)
> 
> 直接更改后，校外指导老师一栏就没有了，会有影响吗

更改什么？为什么要更改？
