### ISSUE TITLE
给附录打的\label用\autoref引用时显示英文

### ISSUE THREAD

**Issue by iTomxy** [sikouhjw/gdutthesis#67]
有一节附录，并对该附录的 chapter 打了个 label：
```latex
%...
\gdutappendix

\chapter{符}{bar}
\label{app:foo-bar}
%...

\end{document}
```
生成的附录标题显示为：
![app](https://user-images.githubusercontent.com/44149820/162585178-5108068c-5f58-4096-95d5-05aefcad366d.png)
然后在前面某章节用 `\autoref{app:foo-bar}` 引用，显示为：
![1649525849(1)](https://user-images.githubusercontent.com/44149820/162585232-704058e1-54a8-41f9-9a77-17c46d6b44e5.png)
预期是应该像图、表那样将 `Appendix` 显示为中文的 `附录` 才对？

**Comment by sikouhjw** [comment]
在导言区加
```tex
\newcommand{\appendixautorefname}{附录}
```
之前弄 `\autoref` 的时候没注意附录还需要定制。
