### ISSUE TITLE
关于增添"是否双导师"的选项

### ISSUE THREAD

**Issue by House-Leo** [sikouhjw/gdutthesis#7]
感谢对学校latex模版的贡献，也希望尽早能通过各种研究生院的审核。提个意见：

如果不需要双导师的话，自己懂latex的话可以在clc文件上把第1470和1471行都注释掉
https://github.com/sikouhjw/gdutthesis/blob/85d6d71b26f3be01fef1b6c5fa5b2c7935a5d2fc/gdutthesis.cls#L1470-L1471
不过建议加入选择是否双导师的选项

**Comment by sikouhjw** [comment]
不填双导师不就行了？
新的扉页没有说『没有双导师』就不要『这一行』。

**Comment by House-Leo** [comment]
![image](https://user-images.githubusercontent.com/47940711/142850731-fac9445a-6d67-4a6f-b5e6-676b92174215.png)
不注释的话会多出来空白的一行

**Comment by sikouhjw** [comment]
> ![image](https://user-images.githubusercontent.com/47940711/142850731-fac9445a-6d67-4a6f-b5e6-676b92174215.png) 不注释的话会多出来空白的一行

也没有说『空白的一行』是错的，我的看法是随意，我不觉得会因为这个过不了格式审查。

我新提交的代码解决了这个问题，写 `none` 就可以了。
