### ISSUE TITLE
公式中英文花体与原先使用有出入

### ISSUE THREAD

**Issue by mycano** [sikouhjw/gdutthesis#78]
一般情况下，英文论文较多使用/mathcal{}花体字，但模板中mathcal的花体比英文论文“更加花体”，如图所示：
![image](https://user-images.githubusercontent.com/44746611/201451794-afed17f8-6549-4391-b381-e7decbe4e6f2.png)

想看看能否适配下面这种：
![image](https://user-images.githubusercontent.com/44746611/201451908-33a92506-6796-4593-882d-18dc57991d70.png)

**Comment by sikouhjw** [comment]
参考《[【LaTeX/unicode-math】使用不同风格的「花体」字母](https://zhuanlan.zhihu.com/p/569922028)》，`\mathcal` 和 `\mathscr` 其实是同一个东西，我认为没有区分的必要。

如果非要区分，参考这段代码
```tex
\documentclass{gdutthesis}

\gdutsetup{
  style = {
    math-font       = {times},
  },
}

\setmathfont{XITS Math}[StylisticSet=1, range=cal]

\begin{document}
  \[ \mathcal{ABC} \mathscr{ABC} \]
  \[ \symcal{ABC}  \symscr{ABC}  \]
\end{document}
```
