### ISSUE TITLE
该版本模板编译后没有参考文献部分

### ISSUE THREAD

**Issue by GDUT-Kyle** [sikouhjw/gdutthesis#80]
作者您好，我下载的`gdutthesis v0.1e`编译后，pdf没有生成相应的参考文献部分，参数配置如下：
```
		bib-backend     = {bibtex},
%		bib-backend     = {biblatex},
		bib-resource    = {ref/gdutthesis-template.bib},
		bib-style       = {numerical},

\nocite{*}% 列出全部参考文献
\printbibliography
```
希望能得到您的帮助，感谢！

**Comment by sikouhjw** [comment]
用 `bibtex` 编译，或者使用 `latexmk -xelatex main.tex`

**Comment by miniyia** [comment]
同学你好，请问你解决了吗？

**Comment by majiajun1** [comment]
> 用 `bibtex` 编译，或者使用 `latexmk -xelatex main.tex`

用这个就好  希望后续能在readme加上这个提示   texstudio要手动加脚本才行  折腾半天了
