### ISSUE TITLE
参考文献列表存在大量无关信息

### ISSUE THREAD

**Issue by XingyanMao** [sikouhjw/gdutthesis#82]
我通过zotero文献库与overleaf连接，获得的bib文件

这就导致了我的bib文件里面有很多字段，比如url，issn，doi，语言。
![image](https://user-images.githubusercontent.com/50959195/222678579-71b3b83a-3360-4f25-a54e-a88198611471.png)

以及一些与参考文献无关的资料信息（并未引用）
![image](https://user-images.githubusercontent.com/50959195/222678114-638fc893-ad73-4d62-bc60-5c8871530f55.png)
需要注意：正文中引用数并未高达200+文献（200+是我文献库中所有文献的数量）

在主文件编译完成后，上述这些信息全部在参考文献列表中出现了。请问该问题应当如何解决？

**Comment by note286** [comment]
建议选择一个熟悉的文本编辑器修改`.bib`文件，批量移除。

**Comment by sikouhjw** [comment]
> 这就导致了我的bib文件里面有很多字段，比如url，issn，doi，语言。 

你认为这些字段『不应该』出现在参考文献列表，但这些字段在国标中都规定了可以出现，因此『不要管』这些字段，让它们自己输出即可。

如果你认为『过不了审查』，实际上没有被审查拦下来的案例。如果你认为『你导师不喜欢』，你可以拿国标去辩论。如果辩论不过，可以去读 `texdoc gbt7714` 或 `texdoc biblatex-gb7714` 的手册来解决，也可以参考《参考文献集中定制需求》[^1]。

[^1]: https://github.com/sikouhjw/gdutthesis/discussions/68

> 以及一些与参考文献无关的资料信息（并未引用）
> 需要注意：正文中引用数并未高达200+文献（200+是我文献库中所有文献的数量）
> 在主文件编译完成后，上述这些信息全部在参考文献列表中出现了。请问该问题应当如何解决？

这是因为
https://github.com/sikouhjw/gdutthesis/blob/19b068e9ef1685443204040206dace634b927228/main.tex#L130
注释即可。
