### ISSUE TITLE
交叉引用的时候显示的文本有红色

### ISSUE THREAD

**Issue by TungyuYoung** [sikouhjw/gdutthesis#87]
我发现交叉引用的时候，即图1-1、表1-1之类的，正文里显示的文本是红色的。
对于参考文献的引用，那个数字则是绿色。
请问如何取消颜色的显示呢？

**Comment by sikouhjw** [comment]
https://github.com/sikouhjw/gdutthesis/blob/f7e5fd504bb3c220d9708d9573630236ed0d793c/user-manual/gdutthesis.dtx#L1299-L1307
请阅读手册后再使用。
