### ISSUE TITLE
缩略词表无法编译成功，且在不需要物理量名称及符号表的时候，直接注释掉\input{data/notation.tex}会报错

### ISSUE THREAD

**Issue by TungyuYoung** [sikouhjw/gdutthesis#88]
缩略词表无法编译成功，且在不需要物理量名称及符号表的时候，直接注释掉\input{data/notation.tex}会报错

**Comment by sikouhjw** [comment]
> 缩略词表无法编译成功

https://github.com/sikouhjw/gdutthesis/blob/f7e5fd504bb3c220d9708d9573630236ed0d793c/user-manual/gdutthesis.dtx#L737-L746
请使用 `latexmk -xelatex` 编译

> 且在不需要物理量名称及符号表的时候，直接注释掉\input{data/notation.tex}会报错

在本地环境无法复现，在 Overleaf 也无法复现，请你提供更具体的信息：从哪下的模板、改了什么、本地环境是 TeX Live
 哪个版本、编译命令是什么，或者将内容脱敏后发到 support_gdutthesis@163.com 邮箱

**Comment by sikouhjw** [comment]
通过邮件联系的后续：
1. 缩略词表可以编译成功，问题在于新增的缩略词没有出现在词表中
2. 该问题的原因在于没有在正文中使用 `\gls` 命令，使用后问题解决
3. 『注释掉\input{data/notation.tex}会报错』的问题，其本人已解决且后续无法复现
