### ISSUE TITLE
未来打算更新支持pdfLatex编译的模板吗？

### ISSUE THREAD

**Issue by lvhzgit** [sikouhjw/gdutthesis#89]
我用的是Texstudio+TexLive，这个也是比较常用的配置。当然用Overleaf更方便但网络不稳定时候比较麻烦。TexStudio支持XeLatex编译，但是在公式预览时候还是用pdfLatex，不支持XeLatex。即鼠标悬停在数学环境上方时，会在窗口下方用pdfLatex预编译显示公式。

**Comment by note286** [comment]
你可以使用lualatex预览。

**Comment by lvhzgit** [comment]
> 这个也不支持，也不知道是不是Texstudio有毒。

------------------------------------------------------------------------------------
开始 : lualatex.exe -interaction=nonstopmode -ini "&lualatex hQBdHZi \dump"

开始 : lualatex.exe -synctex=1 -interaction=nonstopmode "nzoAEu".tex

出现错误

出现错误

开始 : lualatex.exe -synctex=1 -interaction=nonstopmode "CLcBPN".tex

出现错误
---------------------------------------------------------------------------------------------


不过，编译预览是没问题的
---------------------------------------------------------------------------------------------
开始 : xelatex.exe -synctex=1 -interaction=nonstopmode "main".tex

完成
---------------------------------------------------------------------------------------------

**Comment by note286** [comment]
预览中的`pdflatex`不是指`pdflatex.exe`，而是设置中的名为`pdflatex`的配置。

**Comment by sikouhjw** [comment]
该理由不充分，且模板在技术上不可能换回 pdflatex，在个人经验上，pdflatex 也容易出问题，最后麻烦的还是我

**Comment by lvhzgit** [comment]
感谢前辈解答，这个方案最好按作者给的pdf说明文档，命令行编译最稳当。还有gdutcite{}没有文献提示，这个用起来虽然比平常期刊论文费劲但是比word方便很多，我目前的方案是先用cite{}之后再关键词替换成gdutcite{}。看看前辈后续会不会能不能更新gdutcite{}文献提示吧。做模板cls这东西确实相当麻烦，能有人组织做我都觉得很难得了。

**Comment by sikouhjw** [comment]
> 还有gdutcite{}没有文献提示，这个用起来虽然比平常期刊论文费劲但是比word方便很多，我目前的方案是先用cite{}之后再关键词替换成gdutcite{}。看看前辈后续会不会能不能更新gdutcite{}文献提示吧。

`\gdutcite` 是为了统一两种不同 bib 处理方式下的引用命令
https://github.com/sikouhjw/gdutthesis/blob/f7e5fd504bb3c220d9708d9573630236ed0d793c/gdutthesis.cls#L1712-L1741
在 https://github.com/zepinglee/gbt7714-bibtex-style/issues/95#issuecomment-1067924571 中，提供了一种解决方案，即使用 `\cite` 和 `\parencite` 来引用：
- 如果发行版是最新的，那可以直接使用 `\cite` 和 `\parencite` 来引用
- 如果发行版不是最新的，可以在导言区定义 bibtex 下的 `\parencite`

后续我再把 `\gdutcite` 删掉，换成 `\cite` 和 `\parencite`
