### ISSUE TITLE
导入论文封皮后正文排版出现

### ISSUE THREAD

**Issue by coallar** [sikouhjw/gdutthesis#92]
使用cover-background中的master封皮后，后续内容会影响，正文居中，请问怎么解决呢？
![image](https://user-images.githubusercontent.com/66529823/231473478-125e1ec5-82eb-4271-81ac-51031838ab88.png)

![image](https://user-images.githubusercontent.com/66529823/231473766-db134c1e-f183-49d8-a764-bce900429c28.png)

**Comment by sikouhjw** [comment]
在 https://github.com/sikouhjw/gdutthesis/commit/ecbc4206e6b4bc67ffe839e9a002e051120125f9 修复了，下载最新的模板 https://github.com/sikouhjw/gdutthesis/archive/refs/heads/main.zip 即可。
