### ISSUE TITLE
跨页表格longtable配合“\bicaption”命令报错

### ISSUE THREAD

**Issue by lvhzgit** [sikouhjw/gdutthesis#97]
latex源码：

\begin{longtable}
	\bicaption{xxxxxxxxxxx}{yyyyyyyyyyyyyy}
	\label{tab:zzzzzzz}\\
	\begin{tabular}{lccc}
        \toprule
        hbla &hbla &hbla &hbla &hbla
        \midrule
        bla &bla &bla &bla &bla
        bla &bla &bla &bla &bla
        bla &bla &bla &bla &bla
        bla &bla &bla &bla &bla
        \bottomrule
	\end{tabular}
\end{longtable}

报错内容：
Package array Error: Illegal pream-token (\bicaption): `c' used. ^^I\bicaption

**Comment by sikouhjw** [comment]
1. 这跟模板无关，这是基础使用问题
2. 这个问题请你阅读 `texdoc longtable`，查看 `longtable` 的用法
3. 可以参考以下代码来学习使用 `longtable`
```tex
\documentclass{article}
\usepackage{longtable,bicaption}
\begin{document}
\begin{longtable}{@{*}r||p{1in}@{*}}
  KILLED & LINE!!!! \kill
  \bicaption{aa}{A long table\label{long}}\\
  \hline\hline
  \textsc{First}&\textsc{Second}\\
  \hline\hline
  \endfirsthead
  \caption[]{(continued)}\\
  \hline\hline
  \textbf{First}&\textbf{Second}\\
  \hline\hline
  \endhead
  \hline
  This goes at the&bottom.\\
  \hline
  \endfoot
  \hline
  These lines will&appear\\
  in place of the & usual foot\\
  at the end& of the table\\
  \hline
  \endlastfoot
  {longtable}
  columns
  are specified& in the \\
  same way as
  in the {tabular}& environment.\\
  ...
  Lots of lines& like this.\\
  ... \\
  \hline
  Lots\footnote{...} of lines& like this.\\
  Lots
  of
  lines& like this\footnote{...}\\
  \hline
  Lots of lines& like this.\\
  ...
\end{longtable}
\end{document}
```

**Comment by sikouhjw** [comment]
https://github.com/sikouhjw/gdutthesis/blob/f1c4819f4c2d846d2e5a6b91f8e887063bb35463/gdutthesis.cls#L1501-L1511
`notation` 环境是用 `longtable` 做的，所以你的需求已经实现了。
